### PR TITLE
feat(InfoButton): Added info button with popup

### LINKED ISSUE #54: Create info-button
Skjermbilde 2020-09-21 kl  20 37 52

This needs more description. @AnneMatilde can you pitch in?

### PR DESCRIPTION
**Pull request by TanyaDolgopolova**
Code cleaning
Screenshot 2020-10-16 at 16 08 09

Close #54

### CODE REVIEW

**Review by cobraz — CHANGES_REQUESTED** [review]
Skjermbilde 2020-10-20 kl  23 00 23

Looks like it is possible to go out of canvas. 👆

**Comment by TanyaDolgopolova** [comment]
@cobraz hi, for fixing this issue with going out of canvas I add logic for checking the size of popup relative to the empty size from the top. If there is no empty space, will be showing from the bottom of the button and vice versa.

**Comment by cobraz** [comment]
Maybe we should postpone this? We don't currently need it (for Project Barebone)

**Comment by TanyaDolgopolova** [comment]
> Maybe we should postpone this? We don't currently need it (for Project Barebone)

Yeah,

> Maybe we should postpone this? We don't currently need it (for Project Barebone)

Okay. I will start doing issues from Backoffice project

**Pull request closed without merging**
